### ISSUE TITLE
Documentation link doesn't work

### ISSUE THREAD

**Issue by heggiedavid** [pimoroni/gfx-hat#11]
The link in the main README.md ("Guides and Tutorials" to https://learn.pimoroni.com/gfx-hat) doesn't work - opens a blank page with no content.

**Comment by Gadgetoid** [comment]
A quick look at Archive.org suggests there were never any Graphics HAT guides or tutorials I'm afraid. But thanks for reporting the broken link- I'll remove it until we can get some content up there.
